name: Test SimpleToast

on:
  pull_request:
    paths:
      - "**.swift"

jobs:
  swifttesting:
    runs-on: [macOS, self-hosted]
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftTesting
        uses: GetAutomaApp/opensource-actions/swifttesting@main
        with:
          working-directory: "."
          compose: "false"
